stages:
  - build
  - test

# Shooter API pipeline items:

test pin_api:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - "cd pin_api/participantapi_tests"
    - "dotnet test"

# pin_ui pipeline items:

build pin_ui:
  stage: build
  image: node:12.15
  script:
    - "cd pin_ui/pinmentor"
    - "npm install"
    - "npm install -g @vue/cli"
    - "npm run build"