# Based on https://vuejs.org/v2/cookbook/dockerize-vuejs-app.html
FROM node:lts-alpine AS buildenv

RUN npm install -g http-server

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 8080

CMD [ "http-server", "dist"]